version: "3.8"
volumes:
  packages:
    driver: local
services:
  pypiserver:
    container_name: pypiserver
    image: pypiserver/pypiserver:latest
    volumes:
      - type: volume
        source: packages
        target: /data/packages
    command: -P . -a . /data/packages
    ports:
      - "50000:8080"
    restart: on-failure