version: "3.8"
services:
  jupyter:
    container_name: nnabla-jupyter
    build: .
    volumes:
      - type: bind
        source: ./notebooks
        target: /working
    ports:
      - "50002:8888"
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    entrypoint: jupyter notebook --ip=0.0.0.0 --allow-root --NotebookApp.token=nnabla
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all