version: "3.8"
services:
  jupyter:
    container_name: tensorflow-jupyter
    image: tensorflow/tensorflow:latest-gpu-jupyter
    volumes:
      - type: bind
        source: `pwd`/notebooks
        target: /tf
    ports:
      - "8888:8888"
    restart: on-failure
# GPU使用時
#    runtime: nvidia
#    environment:
#      - NVIDIA_VISIBLE_DEVICES=all
#      - NVIDIA_DRIVER_CAPABILITIES=all