version: "3.8"
services:
  jupyter:
    container_name: tensorflow-jupyter
    image: tensorflow/tensorflow:latest-gpu-jupyter
    volumes:
      - type: bind
        source: ./notebooks
        target: /tf
    ports:
      - "50001:8888"
    restart: on-failure
#    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all